version: '3.8'
services:
  server:
    build:
      context: ./packages/server/.
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/server-1
    stdin_open: true
    tty: true
  client:
    build:
      context: ./packages/client/.
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    depends_on:
      - server
    volumes:
      - .:/client-1
    stdin_open: true
    tty: true